name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run : git config --global user.name github-actions && git config --global user.email github-actions@github.com && npm i && npm run deploy -- -m "Deploy React app to GitHub Pages"
      shell: bash
      
