name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm i
      shell: bash
    - run : npm run deploy -- -m "Deploy React app to GitHub Pages"
      shell: bash
      
